# Generated by Django 5.2.8 on 2025-11-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_currency", models.CharField(db_index=True, max_length=3)),
                ("destination_currency", models.CharField(db_index=True, max_length=3)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=20)),
                ("source_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "destination_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "exchange_rates",
                "indexes": [
                    models.Index(
                        fields=["source_currency", "destination_currency"],
                        name="exchange_ra_source__50bcfe_idx",
                    ),
                    models.Index(
                        fields=["last_updated"], name="exchange_ra_last_up_6991c4_idx"
                    ),
                ],
                "unique_together": {("source_currency", "destination_currency")},
            },
        ),
    ]
